// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxBqPf-j4dVja7jzYyBrsJrxIvNFlVYK8',
    appId: '1:733079383338:web:88a691ff754ad87b790253',
    messagingSenderId: '733079383338',
    projectId: 'kigali-city-services-c4436',
    authDomain: 'kigali-city-services-c4436.firebaseapp.com',
    storageBucket: 'kigali-city-services-c4436.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyNCF1eijAFSthUFuEYcpLjkX6f19I5s',
    appId: '1:733079383338:android:b67e911ffcd46a41790253',
    messagingSenderId: '733079383338',
    projectId: 'kigali-city-services-c4436',
    storageBucket: 'kigali-city-services-c4436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkwfizSCXAD0g2EtuDNsizg6_6kiF4Kw',
    appId: '1:733079383338:ios:b761a42e27663ea0790253',
    messagingSenderId: '733079383338',
    projectId: 'kigali-city-services-c4436',
    storageBucket: 'kigali-city-services-c4436.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkwfizSCXAD0g2EtuDNsizg6_6kiF4Kw',
    appId: '1:733079383338:ios:b761a42e27663ea0790253',
    messagingSenderId: '733079383338',
    projectId: 'kigali-city-services-c4436',
    storageBucket: 'kigali-city-services-c4436.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxBqPf-j4dVja7jzYyBrsJrxIvNFlVYK8',
    appId: '1:733079383338:web:785c9eff59597cdd790253',
    messagingSenderId: '733079383338',
    projectId: 'kigali-city-services-c4436',
    authDomain: 'kigali-city-services-c4436.firebaseapp.com',
    storageBucket: 'kigali-city-services-c4436.firebasestorage.app',
  );
}
